title: Corona Info Nepal
email: budhram.gurung01@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Get the reliable and authentic information regarding COVID-19 disease
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coronainfonepal.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# images_base_url: /assets # for local images
images_base_url:  https://coolbrg.sirv.com/Images/coronainfonepal.org/ # for cdn based images

google_analytics: # UA-162159392-1
permalink: /blogs/:year/:month/:day/:title/
future: true

languages: ["np", "en"]
exclude_from_localizations:
  - "assets"
  - "script"
  - "README.md"
  - "Rakefile"
  - "feed.xml"

# pagination:
#   enabled: true
#   per_page: 10
#   permalink: '/page/:num/'
#   sort_reverse: true

collections:
  infos:
    output: true
  infos_en:
    output: true
  videos:
    output: true
  videos_en:
    output: true

sass:
  sass_dir : _sass
  style    : :compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-multiple-languages-plugin

exclude:
  - _blogs
  - Gemfile
  - Gemfile.lock
